version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 2
    versioning-strategy: increase
    ignore:
      - dependency-name: '@types/node'
        versions:
          - '>=13'
